name: setup-workflow-monitor
description: "Sets up a daemon to track when the manager should be torn down."

inputs:
  max-runtime-hours:
    description: "Max runtime hours"
    required: true
  platform:
    description: "The platform on which CI is running."
    default: 'aws'

runs:
  using: "composite"
  steps:
    - run: .github/scripts/setup-workflow-monitor.py ${{ inputs.platform }} ${{ inputs.max-runtime-hours }}
      shell: bash
