name: repo-setup
description: "Runs all baseline setup tasks up to scala compilation in the CI container."

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/machinelaunchscript
    - uses: ./.github/actions/buildsetup
