#################################################################################
# For XilinxAlveoInstanceDeployManager RocketTile Split Ring
#################################################################################
xilinx_u250_broadwell_30_soc_30MHz:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: WithDefaultFireSimBridges_WithNoTraceFireSimConfigTweaks_chipyard.BroadwellSbus6RingNoCConfig
  PLATFORM_CONFIG: Remove_BroadwellSbus6RingQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 6-5
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 30
    build_strategy: TIMING
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml

xilinx_u250_broadwell_30_0_30MHz:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: WithDefaultFireSimBridges_WithNoTraceFireSimConfigTweaks_chipyard.BroadwellSbus6RingNoCConfig
  PLATFORM_CONFIG: MTModels_MCRams_Extract_BroadwellSbus6RingQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 6-0
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 30
    build_strategy: TIMING
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml

xilinx_u250_broadwell_30_1_30MHz:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: WithDefaultFireSimBridges_WithNoTraceFireSimConfigTweaks_chipyard.BroadwellSbus6RingNoCConfig
  PLATFORM_CONFIG: MTModels_MCRams_Extract_BroadwellSbus6RingQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 6-1
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 30
    build_strategy: TIMING
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml

xilinx_u250_broadwell_30_2_30MHz:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: WithDefaultFireSimBridges_WithNoTraceFireSimConfigTweaks_chipyard.BroadwellSbus6RingNoCConfig
  PLATFORM_CONFIG: MTModels_MCRams_Extract_BroadwellSbus6RingQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 6-2
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 30
    build_strategy: TIMING
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml

xilinx_u250_broadwell_30_3_30MHz:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: WithDefaultFireSimBridges_WithNoTraceFireSimConfigTweaks_chipyard.BroadwellSbus6RingNoCConfig
  PLATFORM_CONFIG: MTModels_MCRams_Extract_BroadwellSbus6RingQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 6-3
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 30
    build_strategy: TIMING
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml

xilinx_u250_broadwell_30_4_30MHz:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: WithDefaultFireSimBridges_WithNoTraceFireSimConfigTweaks_chipyard.BroadwellSbus6RingNoCConfig
  PLATFORM_CONFIG: MTModels_MCRams_Extract_BroadwellSbus6RingQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 6-4
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 30
    build_strategy: TIMING
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml
