name: build-scala-doc
description: "Compiles Scala Doc"

runs:
  using: "composite"
  steps:
    - run: |
        cat env.sh
        source env.sh
        which conda
        source env.sh && make -C sim scaladoc
      shell: bash
